apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-execution-plans
  namespace: keshi2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/docker/test/execution"